# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QGniTFu1-q0n149eX7ZckwNARfhFYj1P
"""



import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
color_image = cv2.imread('T.jpg',1)
cv2_imshow(color_image)

color_image = cv2.imread('T.jpg',1)
cv2_imshow(color_image)
cv2.imwrite('212221230125VISMAYA.jpg',color_image)

import cv2
color=cv2.imread('T.jpg',1)
print(color.shape)

import cv2
import random
color_image= cv2.imread('T.jpg',1)
for i in range(150):
    for j in range(color_image.shape[1]):
        color_image[i][j] = [random.randint(0,255),random.randint(0,255),random.randint(0,255)]
cv2_imshow(color_image)
cv2.waitKey(0)

import cv2
color_imagw= cv2.imread('T.jpg',-1)
new = color_image[300:450,300:450]
color_image[250:400,250:400] = new
cv2_imshow(color_image)
cv2.waitKey(0)